name: Import open source standard labels

on:
  push:
    branches: [ main ]

jobs:
  labels:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v2
    - name: EddieHubCommunity labels Action
      with:
        node-version: '14'
    - uses: EddieHubCommunity/gh-action-open-source-labels@v0.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        owner-name: 'akebu6'
        repository-name: 'PennyWise'
        force: true # optional to clear existing labels, default to true
        
